server:
  port: 8083

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
        - id: user-service-route
          uri: lb://user-service
          predicates:
            - Path=/api/user-service/**
          filters:
            - StripPrefix=2
            - AddRequestHeader=X-Gateway-Source, gateway
            - name: CircuitBreaker
              args:
                name: userServiceCircuitBreaker
                fallbackUri: forward:/fallback/user-service

        - id: notification-service-route
          uri: lb://notification-service
          predicates:
            - Path=/api/notification-service/**
          filters:
            - StripPrefix=2
            - name: CircuitBreaker
              args:
                name: notificationServiceCircuitBreaker
                fallbackUri: forward:/fallback/notification-service

    consul:
      host: localhost
      port: 8500
      discovery:
        register: true
        service-name: ${spring.application.name}
        health-check-path: /actuator/health
        health-check-interval: 10s
        prefer-ip-address: true
        instance-id: ${spring.application.name}:${random.uuid}
        default-instance-host: host.docker.internal

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 15000
        permittedNumberOfCallsInHalfOpenState: 3
        slowCallRateThreshold: 100
        slowCallDurationThreshold: 2000
    instances:
      userServiceCircuitBreaker:
        baseConfig: default
      notificationServiceCircuitBreaker:
        baseConfig: default

management:
  endpoints:
    web:
      exposure:
        include: "health,info,gateway,routes,circuitbreakers"
  endpoint:
    gateway:
      enabled: true
    circuitbreakers:
      enabled: true