server:
  port: 8083

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
        - id: user-service-route
          uri: lb://user-service
          predicates:
            - Path=/api/user-service/**
          filters:
            - StripPrefix=2
            - AddRequestHeader=X-Gateway-Source, gateway

        - id: notification-service-route
          uri: lb://notification-service
          predicates:
            - Path=/api/notification-service/**
          filters:
            - StripPrefix=2

    consul:
      host: localhost
      port: 8500
      discovery:
        register: true
        service-name: ${spring.application.name}
        health-check-path: /actuator/health
        health-check-interval: 10s
        prefer-ip-address: true
        instance-id: ${spring.application.name}:${random.uuid}
        default-instance-host: host.docker.internal

management:
  endpoints:
    web:
      exposure:
        include: "health,info,gateway,routes"
  endpoint:
    gateway:
      enabled: true