server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/pilyaeva/service-configs.git
          default-label: master
          clone-on-start: true

encrypt:
  key: ${ASTON_HW_CONFIG_ENCRYPT_KEY}

management:
  endpoints:
    web:
      exposure:
        include: health,info,encrypt,decrypt